@startuml

title __SRC's Class Diagram__\n

  package  {
    class AdminUser {
        + AdminUser()
    }
  }
  

  package  {
    abstract class File {
        - author : String
        - description : String
        - fileSize : float
        - typeOfFile : String
        {static} + threshold : float
        + File()
    }
  }
  

  package  {
    class MediaFile {
        - height : int
        - length : int
        {static} + heightThreshold : int
        {static} + lengthThreshold : int
        + MediaFile()
    }
  }
  

  package  {
    class NotRegisteredUser {
        + NotRegisteredUser()
    }
  }
  

  package  {
    class Pdf {
        + Pdf()
    }
  }
  

  package  {
    class Picture {
        + Picture()
    }
  }
  

  package  {
    class Program {
        {static} + main()
    }
  }
  

  package  {
    class RegularUser {
        + RegularUser()
    }
  }
  

  package  {
    abstract class User {
        {static} - counter : int
        - name : String
        - surname : String
        - address : String
        - author : String
        - id : int
        - accessLevel : int
        + getAccessLevel()
        + getName()
        + User()
        + createPdf()
        + createPdf()
        + createWord()
        + createWord()
        + createVideo()
        + createVideo()
        + createPicture()
        + createPicture()
    }
  }
  

  package  {
    class Validator {
        + isSizeIsFine()
        + isResolutionFine()
        + isAccessLevelFine()
    }
  }
  

  package  {
    class Video {
        - duration : double
        + Video()
    }
  }
  

  package  {
    class Word {
        + Word()
    }
  }
  

  AdminUser -up-|> User
  MediaFile -up-|> File
  NotRegisteredUser -up-|> User
  Pdf -up-|> File
  Picture -up-|> MediaFile
  RegularUser -up-|> User
  User o-- Validator : validator
  Video -up-|> MediaFile
  Word -up-|> File


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
